1. Read transactions
2. Verify uniqueness
3. Store in SQL

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('transactions.csv')

In [3]:
df

,Date,Description,Original Description,Amount,Transaction Type,Category,Account Name,Labels,Notes
0,11/25/2022,TST* Mojos Tacos,TST* Mojos Tacos,14.54,debit,Restaurants,CREDIT CARD,NaN,NaN
1,11/25/2022,TST* FRANKLIN FACTORY,TST* FRANKLIN FACTORY,10.70,debit,Restaurants,CREDIT CARD,NaN,NaN
2,11/23/2022,TST* Tavernakaya,TST* Tavernakaya,23.21,debit,Restaurants,CREDIT CARD,NaN,NaN
3,11/23/2022,TST* The Great Dane Pub &,TST* The Great Dane Pub &,9.44,debit,Restaurants,CREDIT CARD,NaN,NaN
4,11/23/2022,BP#9264557PARK STREQPS MADISON WI,BP#9264557PARK STREQPS MADISON WI,39.89,debit,Gas & Fuel,Citi® Double Cash Card,NaN,NaN
...,...,...,...,...,...,...,...,...,...
260,8/29/2022,EXXONMOBIL 99879678,EXXONMOBIL 99879678,12.79,debit,Gas & Fuel,CREDIT CARD,NaN,NaN
261,8/29/2022,TST* Red - Madison,TST* Red - Madison,55.90,debit,Restaurants,CREDIT CARD,NaN,NaN
262,8/29/2022,AMZN Mktp US*VR6AV6C93 Amzn.com/bill WA,AMZN Mktp US*VR6AV6C93 Amzn.com/bill WA,149.89,debit,Shopping,Citi® Double Cash Card,NaN,NaN
263,8/28/2022,GOTHAMBAGELS.COM MADISON WI,GOTHAMBAGELS.COM MADISON WI,8.70,debit,Restaurants,Citi® Double Cash Card,NaN,NaN
264,8/28/2022,FESTIVAL FOODS MADISON WI,FESTIVAL FOODS MADISON WI,49.97,debit,Groceries,Citi® Double Cash Card,NaN,NaN

In [6]:
df[df['Transaction Type'] == 'credit']

,Date,Description,Original Description,Amount,Transaction Type,Category,Account Name,Labels,Notes
48,11/07/2022,PAYMENT - THANK YOU,PAYMENT - THANK YOU,2723.45,credit,Credit Card Payment,Citi® Double Cash Card,NaN,NaN
75,11/02/2022,STEAM PURCHASE 425-9522985 WA,STEAM PURCHASE 425-9522985 WA,21.09,credit,Income,Citi® Double Cash Card,NaN,NaN
77,11/01/2022,AUTOMATIC PAYMENT - THANK,AUTOMATIC PAYMENT - THANK,1104.72,credit,Credit Card Payment,CREDIT CARD,NaN,NaN
84,10/28/2022,HAMPTON INN & SUITES BAL,HAMPTON INN & SUITES BAL,446.48,credit,Hotel,CREDIT CARD,NaN,NaN
145,10/07/2022,PAYMENT THANK YOU,PAYMENT THANK YOU,1496.38,credit,Credit Card Payment,Citi® Double Cash Card,NaN,NaN
147,10/06/2022,Thankyou Points Redeemed TY OR192654876,Thankyou Points Redeemed TY OR192654876,330.25,credit,Income,Citi® Double Cash Card,NaN,NaN
163,9/30/2022,AUTOMATIC PAYMENT - THANK,AUTOMATIC PAYMENT - THANK,947.41,credit,Credit Card Payment,CREDIT CARD,NaN,NaN
232,9/07/2022,PAYMENT THANK YOU,PAYMENT THANK YOU,1516.87,credit,Credit Card Payment,Citi® Double Cash Card,NaN,NaN
250,9/02/2022,STEAM PURCHASE 425-9522985 WA,STEAM PURCHASE 425-9522985 WA,10.54,credit,Income,Citi® Double Cash Card,NaN,NaN
252,9/01/2022,AUTOMATIC PAYMENT - THANK,AUTOMATIC PAYMENT - THANK,2085.65,credit,Credit Card Payment,CREDIT CARD,NaN,NaN

In [7]:
df['Category'].unique()

array(['Restaurants', 'Gas & Fuel', 'Fast Food', 'Groceries',
       'Service & Parts', 'Entertainment', 'Shopping', 'Gym',
       'Furnishings', 'Hotel', 'Alcohol & Bars', 'Travel', 'Coffee Shops',
       'Parking', 'Ride Share', 'Internet', 'Utilities',
       'Credit Card Payment', 'Television', 'Auto Insurance', 'Income',
       'Hair', 'Gifts & Donations', 'Spa & Massage', 'Food & Dining',
       'Food Delivery', 'Books', 'Amusement', 'Business Services',
       'Service Fee', 'Newspapers & Magazines', 'Electronics & Software',
       'Pharmacy', 'Pet Food & Supplies', 'Music', 'Arts', 'Sports'],
      dtype=object)

In [8]:
df['Labels'].unique()

array([nan])

In [3]:
import csv

with open('mint transactions/transactions.csv') as f:
    reader = csv.reader(f)
    lines = [x for x in reader]

In [4]:
import hashlib

data = []
expected_columns = ['Date', 'Description', 'Original Description', 'Amount', 'Transaction Type', 
                    'Category', 'Account Name', 'Labels', 'Notes']
filepath = 'mint transactions/transactions.csv'

with open(filepath) as f:
    reader = csv.reader(f)
    
    columns = next(reader)
    if columns != expected_columns:
        raise Error(f'Columns do not equal expected columns in {filepath}!')
    
    for tx in reader:
        old_date = tx[0]
        month, day, year = old_date.split('/')
        new_date = year + '-' + month + '-' + day
        print(new_date)
        tx_id = hashlib.sha256((new_date + tx[1] + tx[3] + tx[4]).encode('utf-8')).hexdigest()
        data.append((tx_id, new_date, tx[1], tx[3], tx[4], tx[6], tx[5]))

2022-11-25
2022-11-25
2022-11-23
2022-11-23
2022-11-23
2022-11-23
2022-11-23
2022-11-22
2022-11-22
2022-11-20
2022-11-19
2022-11-19
2022-11-18
2022-11-18
2022-11-17
2022-11-17
2022-11-17
2022-11-16
2022-11-14
2022-11-14
2022-11-14
2022-11-14
2022-11-14
2022-11-14
2022-11-14
2022-11-14
2022-11-13
2022-11-13
2022-11-13
2022-11-13
2022-11-13
2022-11-13
2022-11-13
2022-11-13
2022-11-13
2022-11-13
2022-11-12
2022-11-11
2022-11-11
2022-11-11
2022-11-09
2022-11-09
2022-11-09
2022-11-09
2022-11-08
2022-11-08
2022-11-07
2022-11-07
2022-11-07
2022-11-06
2022-11-06
2022-11-06
2022-11-06
2022-11-06
2022-11-06
2022-11-06
2022-11-06
2022-11-06
2022-11-06
2022-11-06
2022-11-06
2022-11-05
2022-11-05
2022-11-05
2022-11-05
2022-11-04
2022-11-04
2022-11-04
2022-11-04
2022-11-03
2022-11-03
2022-11-03
2022-11-03
2022-11-02
2022-11-02
2022-11-02
2022-11-01
2022-11-01
2022-10-31
2022-10-31
2022-10-31
2022-10-31
2022-10-30
2022-10-29
2022-10-28
2022-10-28
2022-10-28
2022-10-27
2022-10-26
2022-10-25
2022-10-25
2022-10-25
2022-10-24
2022-10-23
2022-10-23
2022-10-23
2022-10-23
2022-10-23
2022-10-22
2022-10-22
2022-10-22
2022-10-22
2022-10-20
2022-10-20
2022-10-19
2022-10-19
2022-10-19
2022-10-19
2022-10-18
2022-10-18
2022-10-18
2022-10-17
2022-10-17
2022-10-17
2022-10-17
2022-10-16
2022-10-16
2022-10-16
2022-10-16
2022-10-16
2022-10-15
2022-10-15
2022-10-14
2022-10-13
2022-10-13
2022-10-12
2022-10-12
2022-10-12
2022-10-12
2022-10-11
2022-10-10
2022-10-10
2022-10-10
2022-10-10
2022-10-09
2022-10-09
2022-10-09
2022-10-09
2022-10-09
2022-10-09
2022-10-09
2022-10-09
2022-10-08
2022-10-08
2022-10-08
2022-10-07
2022-10-07
2022-10-06
2022-10-06
2022-10-06
2022-10-06
2022-10-06
2022-10-05
2022-10-05
2022-10-04
2022-10-04
2022-10-04
2022-10-03
2022-10-02
2022-10-02
2022-10-02
2022-10-02
2022-10-02
2022-9-30
2022-9-30
2022-9-29
2022-9-28
2022-9-28
2022-9-28
2022-9-28
2022-9-27
2022-9-27
2022-9-26
2022-9-26
2022-9-25
2022-9-25
2022-9-24
2022-9-24
2022-9-23
2022-9-23
2022-9-23
2022-9-23
2022-9-23
2022-9-23
2022-9-23
2022-9-23
2022-9-22
2022-9-22
2022-9-22
2022-9-22
2022-9-22
2022-9-22
2022-9-22
2022-9-22
2022-9-22
2022-9-22
2022-9-21
2022-9-21
2022-9-21
2022-9-20
2022-9-19
2022-9-19
2022-9-19
2022-9-19
2022-9-18
2022-9-18
2022-9-18
2022-9-18
2022-9-17
2022-9-17
2022-9-17
2022-9-16
2022-9-16
2022-9-16
2022-9-16
2022-9-15
2022-9-15
2022-9-14
2022-9-13
2022-9-12
2022-9-11
2022-9-11
2022-9-11
2022-9-11
2022-9-11
2022-9-11
2022-9-10
2022-9-10
2022-9-10
2022-9-09
2022-9-08
2022-9-07
2022-9-07
2022-9-07
2022-9-06
2022-9-06
2022-9-06
2022-9-06
2022-9-06
2022-9-06
2022-9-06
2022-9-05
2022-9-05
2022-9-04
2022-9-04
2022-9-04
2022-9-04
2022-9-04
2022-9-03
2022-9-02
2022-9-02
2022-9-02
2022-9-01
2022-9-01
2022-9-01
2022-9-01
2022-9-01
2022-9-01
2022-8-31
2022-8-31
2022-8-29
2022-8-29
2022-8-29
2022-8-28
2022-8-28

In [32]:
import sqlite3

con = sqlite3.connect('transactions.db')
cur = con.cursor()

cur.executemany('INSERT OR IGNORE INTO transactions VALUES(?, ?, ?, ?, ?, ?, ?)', data)
con.commit()

In [36]:
cur.execute('SELECT * FROM transactions')
txs = [row for row in cur]
len(txs)

264

In [37]:
import os

os.listdir('mint transactions')

['transactions.csv']

In [39]:
['mint transactions/' + fn for fn in os.listdir('mint transactions') if fn.endswith('.csv')]

['mint transactions/transactions.csv']

In [10]:
import sqlite3

con = sqlite3.connect('transactions.db')
cur = con.cursor()

cur.execute('SELECT * FROM transactions')
txs = [row for row in cur]
len(txs)

264

In [12]:
for tx in txs:
    print(tx[1])

2022-11-25
2022-11-25
2022-11-23
2022-11-23
2022-11-23
2022-11-23
2022-11-23
2022-11-22
2022-11-22
2022-11-20
2022-11-19
2022-11-19
2022-11-18
2022-11-18
2022-11-17
2022-11-17
2022-11-17
2022-11-16
2022-11-14
2022-11-14
2022-11-14
2022-11-14
2022-11-14
2022-11-14
2022-11-14
2022-11-14
2022-11-13
2022-11-13
2022-11-13
2022-11-13
2022-11-13
2022-11-13
2022-11-13
2022-11-13
2022-11-13
2022-11-13
2022-11-12
2022-11-11
2022-11-11
2022-11-11
2022-11-09
2022-11-09
2022-11-09
2022-11-09
2022-11-08
2022-11-08
2022-11-07
2022-11-07
2022-11-07
2022-11-06
2022-11-06
2022-11-06
2022-11-06
2022-11-06
2022-11-06
2022-11-06
2022-11-06
2022-11-06
2022-11-06
2022-11-06
2022-11-06
2022-11-05
2022-11-05
2022-11-05
2022-11-05
2022-11-04
2022-11-04
2022-11-04
2022-11-04
2022-11-03
2022-11-03
2022-11-03
2022-11-03
2022-11-02
2022-11-02
2022-11-02
2022-11-01
2022-11-01
2022-10-31
2022-10-31
2022-10-31
2022-10-31
2022-10-30
2022-10-29
2022-10-28
2022-10-28
2022-10-28
2022-10-27
2022-10-26
2022-10-25
2022-10-25
2022-10-25
2022-10-24
2022-10-23
2022-10-23
2022-10-23
2022-10-23
2022-10-23
2022-10-22
2022-10-22
2022-10-22
2022-10-22
2022-10-20
2022-10-20
2022-10-19
2022-10-19
2022-10-19
2022-10-19
2022-10-18
2022-10-18
2022-10-18
2022-10-17
2022-10-17
2022-10-17
2022-10-17
2022-10-16
2022-10-16
2022-10-16
2022-10-16
2022-10-16
2022-10-15
2022-10-15
2022-10-14
2022-10-13
2022-10-13
2022-10-12
2022-10-12
2022-10-12
2022-10-12
2022-10-11
2022-10-10
2022-10-10
2022-10-10
2022-10-10
2022-10-09
2022-10-09
2022-10-09
2022-10-09
2022-10-09
2022-10-09
2022-10-09
2022-10-09
2022-10-08
2022-10-08
2022-10-08
2022-10-07
2022-10-07
2022-10-06
2022-10-06
2022-10-06
2022-10-06
2022-10-06
2022-10-05
2022-10-05
2022-10-04
2022-10-04
2022-10-04
2022-10-03
2022-10-02
2022-10-02
2022-10-02
2022-10-02
2022-10-02
2022-09-30
2022-09-30
2022-09-29
2022-09-28
2022-09-28
2022-09-28
2022-09-28
2022-09-27
2022-09-27
2022-09-26
2022-09-26
2022-09-25
2022-09-25
2022-09-24
2022-09-24
2022-09-23
2022-09-23
2022-09-23
2022-09-23
2022-09-23
2022-09-23
2022-09-23
2022-09-22
2022-09-22
2022-09-22
2022-09-22
2022-09-22
2022-09-22
2022-09-22
2022-09-22
2022-09-22
2022-09-22
2022-09-21
2022-09-21
2022-09-21
2022-09-20
2022-09-19
2022-09-19
2022-09-19
2022-09-19
2022-09-18
2022-09-18
2022-09-18
2022-09-18
2022-09-17
2022-09-17
2022-09-17
2022-09-16
2022-09-16
2022-09-16
2022-09-16
2022-09-15
2022-09-15
2022-09-14
2022-09-13
2022-09-12
2022-09-11
2022-09-11
2022-09-11
2022-09-11
2022-09-11
2022-09-11
2022-09-10
2022-09-10
2022-09-10
2022-09-09
2022-09-08
2022-09-07
2022-09-07
2022-09-07
2022-09-06
2022-09-06
2022-09-06
2022-09-06
2022-09-06
2022-09-06
2022-09-06
2022-09-05
2022-09-05
2022-09-04
2022-09-04
2022-09-04
2022-09-04
2022-09-04
2022-09-03
2022-09-02
2022-09-02
2022-09-02
2022-09-01
2022-09-01
2022-09-01
2022-09-01
2022-09-01
2022-09-01
2022-08-31
2022-08-31
2022-08-29
2022-08-29
2022-08-29
2022-08-28
2022-08-28

In [9]:
old = '9/1/2022'
month, day, year = [int(x) for x in old.split('/')]
f'{year}-{month:02d}-{day:02d}'

'2022-09-01'

In [16]:
start = '2022-10-01'
end = '2022-10-31'

cur = con.cursor()
command = f'''
    SELECT * FROM transactions
    WHERE date >= {start} AND date < {end}
'''
cur.execute(command)

In [18]:
[row for row in cur]

[]

In [19]:
cur = con.cursor()
cur.execute('''
    SELECT * FROM transactions
    WHERE date >= '2022-10-01' AND date < '2022-11-01'
''')
for row in cur:

[('237edbf91ce4e9a8f05b12f74524a228ddc9c8b1e4d591321823f0b9f5a8a98a',
  '2022-10-31',
  'TST* Tavernakaya',
  45.26,
  'debit',
  'Restaurants',
  'CREDIT CARD'),
 ('0e42f1e56d3dffe348b328f2049746eaf36997c3fa7e833efc50344522b459fc',
  '2022-10-31',
  'MSN MARKETPLACE MADISON WI',
  7.97,
  'debit',
  'Internet',
  'Citi®\xa0Double Cash Card'),
 ('c5f111db2112e8853e909f3ffd68b5dd9e1fdaff46f94d47d20d9a803b403c04',
  '2022-10-31',
  '665 - DISTRICT MARKET SAN FRANCISCO CA',
  4.99,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('c99ad4e6b91d93327e40063adc6ee49a1b24cdf4ce26b21bfafa7230b8251143',
  '2022-10-31',
  'STEAM PURCHASE 425-9522985 WA',
  21.09,
  'debit',
  'Entertainment',
  'Citi®\xa0Double Cash Card'),
 ('dbe4f3f36328e52d7f2e41ef84fd03b4c782525ebec7ec22d998d2d6efe653c1',
  '2022-10-30',
  'EXXONMOBIL 96319876 MERRIMAC WI',
  6.48,
  'debit',
  'Gas & Fuel',
  'Citi®\xa0Double Cash Card'),
 ('5cea3f4b4af317c495c3013cd1556f21a72c2e2854aa9547a1e3a9698a234ea7',
  '2022-10-29',
  'STOP N SHOP MADISON WI',
  7.49,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('3e51fd36ed06e7f323fdc31805a01cb1a8b975afe19044082a3008c5aad372d2',
  '2022-10-28',
  'HAMPTON INN & SUITES BAL',
  446.48,
  'credit',
  'Hotel',
  'CREDIT CARD'),
 ('36db4a53c81a4a27877b51c6de238072de9e18c24e1edaaf927f09ba115774e1',
  '2022-10-28',
  'TST* Osteria Papavero',
  50.68,
  'debit',
  'Restaurants',
  'CREDIT CARD'),
 ('a81bf2c3e19fca5dc0b16e37acbea8349ae2d196c1a47120ccb6cb5e7b6c932d',
  '2022-10-28',
  'GOPUFF 18554007833 PA',
  25.63,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('7fd5e4bd266a1d58a15566dbb34bf02c69769b67179d48b3785a66d97a34403e',
  '2022-10-27',
  'FESTIVAL FOODS MADISON WI',
  14.8,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('192c963d7dfeba6363b93b4e55af04a3942e334f2cf8aea0a33564b8967f7f7e',
  '2022-10-26',
  'STOP N SHOP MADISON WI',
  4.77,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('a28b9b99a7fbcfc0f40b7d228a2327037354419abcebe6e0c335e5e6ba17e515',
  '2022-10-25',
  'AMZN Mktp US*H872W5UY1 Amzn.com/bill WA',
  9.45,
  'debit',
  'Shopping',
  'Citi®\xa0Double Cash Card'),
 ('9adc8cf92a024dc03f5eb51ad0c3766a4d74204d3ff1e24b113162e37c273617',
  '2022-10-25',
  'BLUE CHIP BARBER CLUB MADISON WI',
  60,
  'debit',
  'Hair',
  'Citi®\xa0Double Cash Card'),
 ('62685a1eac7be95f9eb5a35bdb6afb710db2fb016f72a0ced509d571fc42bce6',
  '2022-10-25',
  'AMZN MKTP US*H001J03X0 AMZN.COM/BILL WA',
  27.41,
  'debit',
  'Shopping',
  'Citi®\xa0Double Cash Card'),
 ('48d66aa79f5dc8eee91b610eacd3ea32f8b139288971e620cc065dfe41740f96',
  '2022-10-24',
  'STEAM PURCHASE 425-9522985 WA',
  6.31,
  'debit',
  'Entertainment',
  'Citi®\xa0Double Cash Card'),
 ('f0346feeb680a4f491517ed858c58db97b17c0eb81260fdf681a25993d689422',
  '2022-10-23',
  'STOP N SHOP MADISON WI',
  4.77,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('8f08863a732676f88e171d7bdc6922f9536c39794d1ae049a94ce7cd73af72ed',
  '2022-10-23',
  'BP#9264995CAPITAL OQPS MADISON WI',
  4.15,
  'debit',
  'Credit Card Payment',
  'Citi®\xa0Double Cash Card'),
 ('bf61c1a82cfe48f9a843ad000e01df5c4c7a0849e5fcfe16ff4a038f9f5bb987',
  '2022-10-23',
  'THE HOUSE ON THE ROCK 608-935-3639 WI',
  28.95,
  'debit',
  'Gifts & Donations',
  'Citi®\xa0Double Cash Card'),
 ('a1277390a08cb3b8947bb4fb0ab742ebc251c253b63cfbb003ebe20d7d545569',
  '2022-10-23',
  'SQ *BARRIQUES Fitchburg WI',
  5.02,
  'debit',
  'Restaurants',
  'Citi®\xa0Double Cash Card'),
 ('528dcd2ebef211ee8e694a3697d9d91533dd3683806b05bbec18eeb330dc4377',
  '2022-10-23',
  'FESTIVAL FOODS MADISON WI',
  27.16,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('47f276a497789e53966b792aeb58b741a92001d5bc9a448bd5e22ea3586e9d02',
  '2022-10-22',
  'GOPUFF 18554007833 PA',
  24.41,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('fb9dfcfb1672e35679ddf1f20b93da7a3b5c002316350bcbc8e55e31e78fecef',
  '2022-10-22',
  'KWIK TRIP 59600005967 BLACK EARTH WI',
  10.26,
  'debit',
  'Gas & Fuel',
  'Citi®\xa0Double Cash Card'),
 ('de7fc8a7101269c88dc4aea689c0541435c010d2bd7378511c88f42c1317d986',
  '2022-10-22',
  'KWIK TRIP 96100009613 MADISON WI',
  11.67,
  'debit',
  'Gas & Fuel',
  'Citi®\xa0Double Cash Card'),
 ('73d9aae1c7dfe39ef6abe0a5afb48fbdeb7c83ae316306d7af445144ede31f58',
  '2022-10-22',
  'KWIK TRIP 59600005967 BLACK EARTH WI',
  4.09,
  'debit',
  'Gas & Fuel',
  'Citi®\xa0Double Cash Card'),
 ('66dd867b16d91cb0c5c7668af5dca9ec71a4303bb11a0e46f0ac595a24d2eb1b',
  '2022-10-20',
  'COLECTIVO COFFEE-MADIS',
  3.69,
  'debit',
  'Coffee Shops',
  'CREDIT CARD'),
 ('075e85bcddd0bda7902b67aee0f39dbf1925a06cfde3d87887b5ac0a9ce6c67a',
  '2022-10-20',
  'AMZN MKTP US*HT85Y0K52 AMZN.COM/BILL WA',
  36.49,
  'debit',
  'Shopping',
  'Citi®\xa0Double Cash Card'),
 ('e128cfdf71c99e07f82d6ef01100c01e00b36ae84275bbf9f5d163b200da13ce',
  '2022-10-19',
  'FESTIVAL FOODS MADISON WI',
  69.23,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('d065fad77a66443c982e15b77f799b8897cc5e2ea511f80733cb1ca53ed6a5f2',
  '2022-10-19',
  'MCW#482 MADISON WI',
  10.55,
  'debit',
  'Service & Parts',
  'Citi®\xa0Double Cash Card'),
 ('858ca2b43ae134651e91e4efa592ef0906167c462e9a3d17b70b06fe993beb65',
  '2022-10-19',
  'AMZN Mktp US*H809R34X1 Amzn.com/bill WA',
  16.87,
  'debit',
  'Shopping',
  'Citi®\xa0Double Cash Card'),
 ('4b1736362bd81586fadc35731358aeb541d83e2a53a2da8326e3c1e7ede426a6',
  '2022-10-19',
  'PAYPAL *ABSLTMASSAG 4029357733 CA',
  65.5,
  'debit',
  'Spa & Massage',
  'Citi®\xa0Double Cash Card'),
 ('9729191541e78c5a12d4edd9053ed2bef14f5bfd7594478c4452270dcafbc200',
  '2022-10-18',
  'THE BRASS RIEATSTREET',
  30.67,
  'debit',
  'Restaurants',
  'CREDIT CARD'),
 ('64f9e648317f5b16e09099aeb0035958d3548d9c06a178868d452727b1866bff',
  '2022-10-18',
  'KWIK TRIP 95600009563 MADISON WI',
  55.58,
  'debit',
  'Gas & Fuel',
  'Citi®\xa0Double Cash Card'),
 ('74de2bc6d1bb5ca9786a5e10f7987feca3b7a1bbea0339cad180c5bbef135da7',
  '2022-10-18',
  'KWIK TRIP 95600009563 MADISON WI',
  2.31,
  'debit',
  'Gas & Fuel',
  'Citi®\xa0Double Cash Card'),
 ('2df4d2ffb7a363534f15dc76849d669f53f2ce30338622baad895fbb8855dd20',
  '2022-10-17',
  'NYTimes*NYTimes 8006984637 NY',
  5,
  'debit',
  'Entertainment',
  'Citi®\xa0Double Cash Card'),
 ('05b8d0418cde8db7f70623d76c8bfc156add1da61c2ef64bb7d03e20f856e8fc',
  '2022-10-17',
  'Boulders Climbing Gym Madison WI',
  136.1,
  'debit',
  'Gym',
  'Citi®\xa0Double Cash Card'),
 ('d550e2bba2ec4a129184b4783c8c39f8525036779d201835ec3e9229d3a01f12',
  '2022-10-17',
  'NYTimes*NYTimes 8006984637 NY',
  17,
  'debit',
  'Entertainment',
  'Citi®\xa0Double Cash Card'),
 ('d71b2d7490900f1b29f6e481181c54e532cf2d4ced881369cb07921d5c02f279',
  '2022-10-17',
  'GOPUFF 18554007833 PA',
  21.43,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('fbc65110e24417c155db7cf9e173891a2452b75e01e6dbff2f95886ca07543fa',
  '2022-10-16',
  "TRADER JOE'S #712  QPS",
  9.48,
  'debit',
  'Groceries',
  'CREDIT CARD'),
 ('523a435afd26b61843cdbd657cb5794b1ef7c98648986ac26271857ae4ebf554',
  '2022-10-16',
  'AMOCO#1999432WILLY QPS MADISON WI',
  9.59,
  'debit',
  'Gas & Fuel',
  'Citi®\xa0Double Cash Card'),
 ('2df259e5231eacc43872560a08529a6cc27d7e5f3b3b94340fc53ef07dacdce7',
  '2022-10-16',
  'FESTIVAL FOODS MADISON WI',
  2.57,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('98127fee50ae8d67e2120ceece4eaf104d0fe71120a514cad89681d86ecd6f30',
  '2022-10-16',
  'SVDP WILLY STORE MADISON WI',
  7.9,
  'debit',
  'Shopping',
  'Citi®\xa0Double Cash Card'),
 ('be4db2f3660ae7cfaf2bd0bc9715dca4d6d741545c6bc473db4412e19be937f2',
  '2022-10-16',
  'TST* Ancora Coffee - K Madison WI',
  18.87,
  'debit',
  'Coffee Shops',
  'Citi®\xa0Double Cash Card'),
 ('cf9fc3db80c64109a4dfc2d74c0e04effcb3e3f4ce0660d83d68eaf0b983778a',
  '2022-10-15',
  'FESTIVAL FOODS MADISON WI',
  31.59,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('e8c0cee2214b0fd33e89f26c2d312f81bf93988bf7e090597e23d5a0803ed4ab',
  '2022-10-15',
  'PP*C L BAKEHOUSE MADISON WI',
  4,
  'debit',
  'Food & Dining',
  'Citi®\xa0Double Cash Card'),
 ('7d9923d74a2c0a36c0c1fb73041572dc5fc88e2e900e26264ac34305f31c99a1',
  '2022-10-14',
  'FESTIVAL FOODS MADISON WI',
  10.01,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('9de2dbba3efcc3c02d4d4b4b535bbe77cebfbcc9026abb0d217443df142fa3a0',
  '2022-10-13',
  'BURROW 6465881588 NY',
  1519.99,
  'debit',
  'Furnishings',
  'Citi®\xa0Double Cash Card'),
 ('4dc513e1018aa41c4776a4c4b95ba82b120fcee3870f7c7efde6807b88d849e2',
  '2022-10-13',
  'HY-VEE FITCHBURG 1184 FITCHBURG WI',
  12.49,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('9c6cc5cd8f74946defeb0fb3ed24adb7de7f694b15e6e7f99c0b3d83909242df',
  '2022-10-12',
  'TST* The Great Dane Pub &',
  14.77,
  'debit',
  'Restaurants',
  'CREDIT CARD'),
 ('a92e7aeb6700bbe3c02b2b4dc1b08793ce176db79b087e594118e6fa01a9fbe1',
  '2022-10-12',
  'STOP N SHOP MADISON WI',
  3.57,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('31cfb017d4a0b9b382bcbe223d7d8efcf56fc652399918dce5d09ef3f827a11b',
  '2022-10-12',
  'STEAM PURCHASE 425-9522985 WA',
  15.81,
  'debit',
  'Entertainment',
  'Citi®\xa0Double Cash Card'),
 ('5a93ff4f3fc02f634c00d0027ff227a0ae79fbbc2b351182ccc12222f7f6193e',
  '2022-10-12',
  'GOPUFF 18554007833 PA',
  22.24,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('01a41fd8a09096874c1a67cfb8f88034113505755e77ed283269653449bd1b73',
  '2022-10-11',
  'KWIK TRIP 95600009563 MADISON WI',
  13.62,
  'debit',
  'Gas & Fuel',
  'Citi®\xa0Double Cash Card'),
 ('79561844afea79e3cae98e5c48f5fe0bbfffe61c0ef712cd2eb78976dfff78b8',
  '2022-10-10',
  'UBER   EATS',
  21.51,
  'debit',
  'Food Delivery',
  'CREDIT CARD'),
 ('10b9212ecb0c1fc4172448f9621fce9dfe4ffa284a684cf421770c0a6dfc31c4',
  '2022-10-10',
  "SQ *BRADBURY'S COFFEE",
  10.44,
  'debit',
  'Coffee Shops',
  'CREDIT CARD'),
 ('fa75ef5eb72738a314e75ee3b0ada7bad12cea257c245abc953a0fc88732cd6f',
  '2022-10-10',
  'MADISON GAS & ELECTRIC 6082527000 WI',
  58.53,
  'debit',
  'Utilities',
  'Citi®\xa0Double Cash Card'),
 ('7f5e73de845b50a16c1c9ec35a4a26346e531c911e09506e8b07abc85dd11904',
  '2022-10-10',
  'HY-VEE FITCHBURG 1184 FITCHBURG WI',
  8.71,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('f4c1bb2c2623540ad79863fb55f190bb7800247d77ccf7f039f5488dae810ea4',
  '2022-10-09',
  'TST* Tavernakaya',
  17.41,
  'debit',
  'Restaurants',
  'CREDIT CARD'),
 ('1cc981fa34ec3090e73c9a52f05b6d65e17a25c11fcae9ba0643438a2d6dc993',
  '2022-10-09',
  'TST* BRASS RING BAR & RES',
  29.5,
  'debit',
  'Restaurants',
  'CREDIT CARD'),
 ('f6e5bc0f6b984debc98ad2b730c9542bb92e5179f5cce170023509b712bcedb7',
  '2022-10-09',
  'A ROOM OF ONE S OWN BO 608-2577888 WI',
  63.29,
  'debit',
  'Books',
  'Citi®\xa0Double Cash Card'),
 ('f66917d29220fb9d24ca273e697ab3d9e4eae88c113ecff979feb9e8e5784ede',
  '2022-10-09',
  'eBay O*18-09192-35445 San Jose CA',
  73.52,
  'debit',
  'Shopping',
  'Citi®\xa0Double Cash Card'),
 ('52bad0027916a569d96c5abbf11ab3c42808e28b4ed9cf6a8fdce9e7a74ba6f8',
  '2022-10-09',
  'FESTIVAL FOODS MADISON WI',
  32.14,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('7ca4f11e472b26f43cfc304d9ec036409c863b1783a6e5ba6a730b57d5f5bd83',
  '2022-10-09',
  'eBay O*12-09194-57624 San Jose CA',
  23.2,
  'debit',
  'Shopping',
  'Citi®\xa0Double Cash Card'),
 ('fff3ce76feefeb5548df91941782c8bf3cc4c3e2fc9a5254fabe9bdce27f8c2b',
  '2022-10-09',
  'GOTHAMBAGELS.COM MADISON WI',
  13.19,
  'debit',
  'Restaurants',
  'Citi®\xa0Double Cash Card'),
 ('178279315b7f2ab2f78987bec94e4895a366c907b5a25d0b690d7afc01d9d999',
  '2022-10-09',
  'SVDP WILLY STORE MADISON WI',
  3.17,
  'debit',
  'Shopping',
  'Citi®\xa0Double Cash Card'),
 ('f04e549c7b6bfded7617af46549bd888ea260d79a3ae47380c837adde1b2765c',
  '2022-10-08',
  'AMOCO#1999432WILLY QPS MADISON WI',
  12.28,
  'debit',
  'Gas & Fuel',
  'Citi®\xa0Double Cash Card'),
 ('1cfac44eaefcc628ce5bda242b8454cef8d6bbae1db65996c4832e197620c5c0',
  '2022-10-08',
  'GOPUFF 18554007833 PA',
  22.35,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('c3805f6868d7fb03b7a8628b253966a96662cd033044c5e0b497e5c94ea7804f',
  '2022-10-08',
  'SQ *WILLY STREET TREAS Madison WI',
  12.66,
  'debit',
  'Food & Dining',
  'Citi®\xa0Double Cash Card'),
 ('5b71a6429286d314579af3907ec497aafb9f47a96695f8188ca08004579f19d2',
  '2022-10-07',
  'PAYMENT THANK YOU',
  1496.38,
  'credit',
  'Credit Card Payment',
  'Citi®\xa0Double Cash Card'),
 ('a371265929c385bbe59521a9309fc08daa279434f523432d2f4c6d42983b9a32',
  '2022-10-07',
  'FH* TALIESIN PRESERVAT SPRING GREEN WI',
  142.04,
  'debit',
  'Amusement',
  'Citi®\xa0Double Cash Card'),
 ('630c98a867564c199e6f9bd0abb962087bbb6694a745ef66ce6dfd5322023d46',
  '2022-10-06',
  'Thankyou Points Redeemed TY OR192654876',
  330.25,
  'credit',
  'Income',
  'Citi®\xa0Double Cash Card'),
 ('87cb97f41b665da5048239cc19a65cbeaaa1dd0368e1379657a7e720f811e591',
  '2022-10-06',
  'WPY*Madison Events Pro 855-999-3729 WI',
  37.98,
  'debit',
  'Business Services',
  'Citi®\xa0Double Cash Card'),
 ('70515e3e67890df6cdcbb72825257110bedee6a9aee18e53ed313541a7ae926e',
  '2022-10-06',
  'GOPUFF 18554007833 PA',
  22.06,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('a9b3bb9b5cf6e59052d95acd5728dc29da193745a654d0edf021676d16b3122a',
  '2022-10-06',
  'FESTIVAL FOODS MADISON WI',
  16.3,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('abbd1cdc981ed8ab4ef95a57cceb6f5b9f525d11fffca5db9fc23ee5dde64619',
  '2022-10-06',
  'KWIK TRIP 95600009563 MADISON WI',
  13,
  'debit',
  'Gas & Fuel',
  'Citi®\xa0Double Cash Card'),
 ('454be73eb0ae306d9576345ac5ab13c4e410a64f410669e26fcd045f752daa95',
  '2022-10-05',
  'FOREIGN TRANSACTION FEE',
  1.01,
  'debit',
  'Service Fee',
  'Citi®\xa0Double Cash Card'),
 ('ea2345426a223fba42db3daa05ba9b54dd853d63b4e1bec7d0d6791557288018',
  '2022-10-05',
  'GOPUFF 18554007833 PA',
  21.82,
  'debit',
  'Groceries',
  'Citi®\xa0Double Cash Card'),
 ('9b870e5ad3dde55b64805ea81edf3ee2ac1427b8316eb0e408a515be31e12091',
  '2022-10-04',
  'ENGELHART, INC MADISON WI',
  31.64,
  'debit',
  'Service & Parts',
  'Citi®\xa0Double Cash Card'),
 ('07423884222d081a6f08dba7854cf765e819dc14b956c34a26bd60fcc70c6aa3',
  '2022-10-04',
  'SQ *THE ROBIN ROOM Madison WI',
  26,
  'debit',
  'Alcohol & Bars',
  'Citi®\xa0Double Cash Card'),
 ('8d35cb74f4721414369fb76bbd83bfd916b5e21b06618d067a1976c5aaed79db',
  '2022-10-04',
  'STATE FARM INSURANCE 8009566310 IL',
  130.99,
  'debit',
  'Auto Insurance',
  'Citi®\xa0Double Cash Card'),
 ('7082938ab776f4e5ea1d986eee3db0c644d18b45532b504b0d757332a4973041',
  '2022-10-03',
  'PRAIRIE ATHLETIC CLUB- 6088374646 WI',
  17,
  'debit',
  'Gym',
  'Citi®\xa0Double Cash Card'),
 ('255aa2ddc47ae0137c2bddef5540e67880980f7b3d45eb3e63414664e4b4f2f6',
  '2022-10-02',
  'NATT SPIL',
  38.38,
  'debit',
  'Restaurants',
  'CREDIT CARD'),
 ('eb168b5299839241c20a3aba1007eee0b287af9490e9c484b130de3d83fc4c4c',
  '2022-10-02',
  'PP*C L BAKEHOUSE',
  12,
  'debit',
  'Restaurants',
  'CREDIT CARD'),
 ('bd064b30a3be31b113fcf107f1bdf5468487a245230b7642d05bfd903a98164e',
  '2022-10-02',
  'AMOCO#1999432WILLY QPS MADISON WI',
  9.35,
  'debit',
  'Gas & Fuel',
  'Citi®\xa0Double Cash Card'),
 ('08826b126a81f2f8fb9333cdf14163e075667490eac44855017821b35e623bb1',
  '2022-10-02',
  'COLECTIVO COFFEE-MADIS MADISON WI',
  4.75,
  'debit',
  'Coffee Shops',
  'Citi®\xa0Double Cash Card'),
 ('0ff6e442416ccb4250bdc6e9ef6b14d4d3fea7d586c69cb29874402dca43fdd2',
  '2022-10-02',
  'CENEX CONSUMER09890419 SAUK CITY WI',
  9.1,
  'debit',
  'Gas & Fuel',
  'Citi®\xa0Double Cash Card')]

In [20]:
page = '''
Important:Auto & Transport
Subcategories
Your subcategories

    Auto Insurance
    Auto Payment
    Gas & Fuel
    Parking
    Public Transportation
    Ride Share
    Service & Parts

Important:Bills & Utilities
Subcategories
Your subcategories

    Home Phone
    Internet
    Mobile Phone
    Television
    Utilities

Important:Business Services
Subcategories
Your subcategories

    Advertising
    Legal
    Office Supplies
    Printing
    Shipping

Important:Education
Subcategories
Your subcategories

    Books & Supplies
    Student Loan
    Tuition

Important:Entertainment
Subcategories
Your subcategories

    Amusement
    Arts
    Movies & DVDs
    Music
    Newspapers & Magazines

Important:Fees & Charges
Subcategories
Your subcategories

    ATM Fee
    Bank Fee
    Finance Charge
    Late Fee
    Service Fee
    Trade Commissions

Important:Financial
Subcategories
Your subcategories

    Financial Advisor
    Life Insurance

Important:Food & Dining
Subcategories
Your subcategories

    Alcohol & Bars
    Coffee Shops
    Fast Food
    Food Delivery
    Groceries
    Restaurants

    Bars & Eating Out

Important:Gifts & Donations
Subcategories
Your subcategories

    Charity
    Gift

Important:Health & Fitness
Subcategories
Your subcategories

    Dentist
    Doctor
    Eyecare
    Gym
    Health Insurance
    Pharmacy
    Sports

Important:Hide from Budgets & Trends
Subcategories
Your subcategories

Important:Home
Subcategories
Your subcategories

    Furnishings
    Home Improvement
    Home Insurance
    Home Services
    Home Supplies
    Lawn & Garden
    Mortgage & Rent

Important:Income
Subcategories
Your subcategories

    Bonus
    Interest Income
    Paycheck
    Reimbursement
    Rental Income
    Returned Purchase

Important:Investments
Subcategories
Your subcategories

    Buy
    Deposit
    Dividend & Cap Gains
    Sell
    Withdrawal

Important:Kids
Subcategories
Your subcategories

    Allowance
    Baby Supplies
    Babysitter & Daycare
    Child Support
    Kids Activities
    Toys

Important:Loans
Subcategories
Your subcategories

    Loan Fees and Charges
    Loan Insurance
    Loan Interest
    Loan Payment
    Loan Principal

Important:Misc Expenses
Subcategories
Your subcategories

Important:Personal Care
Subcategories
Your subcategories

    Hair
    Laundry
    Spa & Massage

Important:Pets
Subcategories
Your subcategories

    Pet Food & Supplies
    Pet Grooming
    Veterinary

Important:Shopping
Subcategories
Your subcategories

    Books
    Clothing
    Electronics & Software
    Hobbies
    Sporting Goods

Important:Taxes
Subcategories
Your subcategories

    Federal Tax
    Local Tax
    Property Tax
    Sales Tax
    State Tax

Important:Transfer
Subcategories
Your subcategories

    Credit Card Payment
    Transfer for Cash Spending

Important:Travel
Subcategories
Your subcategories

    Air Travel
    Hotel
    Rental Car & Taxi
    Vacation

Important:Uncategorized
Subcategories
Your subcategories

    Cash & ATM
    Check
'''

In [36]:
categories = {}
lines = [x.strip() for x in page.split('\n')]
i = 0
print('{')
while i < len(lines):
    if lines[i].startswith('Important:'):
        cat = lines[i].split(':')[1]
        print('    \'' + cat + '\': {', end='')
        i += 4
        subcats = []
        while lines[i] != '' and i < len(lines):
            subcats.append(lines[i])
            print('\'' + lines[i] + '\', ', end='')
            i += 1
        print('\b\b},')
        categories[cat] = subcats
    i += 1
print('\b\b\n}')

{
    'Auto & Transport': {'Auto Insurance', 'Auto Payment', 'Gas & Fuel', 'Parking', 'Public Transportation', 'Ride Share', 'Service & Parts', },
    'Bills & Utilities': {'Home Phone', 'Internet', 'Mobile Phone', 'Television', 'Utilities', },
    'Business Services': {'Advertising', 'Legal', 'Office Supplies', 'Printing', 'Shipping', },
    'Education': {'Books & Supplies', 'Student Loan', 'Tuition', },
    'Entertainment': {'Amusement', 'Arts', 'Movies & DVDs', 'Music', 'Newspapers & Magazines', },
    'Fees & Charges': {'ATM Fee', 'Bank Fee', 'Finance Charge', 'Late Fee', 'Service Fee', 'Trade Commissions', },
    'Financial': {'Financial Advisor', 'Life Insurance', },
    'Food & Dining': {'Alcohol & Bars', 'Coffee Shops', 'Fast Food', 'Food Delivery', 'Groceries', 'Restaurants', },
    'Gifts & Donations': {'Charity', 'Gift', },
    'Health & Fitness': {'Dentist', 'Doctor', 'Eyecare', 'Gym', 'Health Insurance', 'Pharmacy', 'Sports', },
    'Hide from Budgets & Trends': {'Important:Home', 'Subcategories', 'Your subcategories', },
    'Income': {'Bonus', 'Interest Income', 'Paycheck', 'Reimbursement', 'Rental Income', 'Returned Purchase', },
    'Investments': {'Buy', 'Deposit', 'Dividend & Cap Gains', 'Sell', 'Withdrawal', },
    'Kids': {'Allowance', 'Baby Supplies', 'Babysitter & Daycare', 'Child Support', 'Kids Activities', 'Toys', },
    'Loans': {'Loan Fees and Charges', 'Loan Insurance', 'Loan Interest', 'Loan Payment', 'Loan Principal', },
    'Misc Expenses': {'Important:Personal Care', 'Subcategories', 'Your subcategories', },
    'Pets': {'Pet Food & Supplies', 'Pet Grooming', 'Veterinary', },
    'Shopping': {'Books', 'Clothing', 'Electronics & Software', 'Hobbies', 'Sporting Goods', },
    'Taxes': {'Federal Tax', 'Local Tax', 'Property Tax', 'Sales Tax', 'State Tax', },
    'Transfer': {'Credit Card Payment', 'Transfer for Cash Spending', },
    'Travel': {'Air Travel', 'Hotel', 'Rental Car & Taxi', 'Vacation', },
    'Uncategorized': {'Cash & ATM', 'Check', },

}